### PR TITLE
Update to Go 1.21 and Kubernetes 1.28 dependencies

### PR DESCRIPTION
**Pull request by embik**
It has been a while since `pjutil` has been updated, let's bump it from Go 1.18 to 1.21 and from Kubernetes 1.24 to 1.28.

### CODE REVIEW

**Comment by xrstf** [comment]
Why no Go 1.21?

**Comment by embik** [comment]
Because Kubernetes 1.28 also uses Go 1.20. I can bump it to 1.21 though if you care.

**Comment by xrstf** [comment]
Yeah I rarely follow k/k's Go version, but instead my tools usually use the latest Go at the time of writing.

**Comment by embik** [comment]
Updated to Go 1.21.

**Pull request merged**
